import {useEffect,useState} from 'react'
import {loadData,pct} from '../lib/data.js'
export function useSidco(){const [data,setData]=useState(null);const [error,setError]=useState(null);useEffect(()=>{loadData().then(setData).catch(setError)},[]);return {data,error}}
export function Loading({error}){return <div className="rounded-2xl border bg-white p-8 text-sm text-slate-600">{error?`Error: ${error.message}`:'Cargando fuente SIDCO sintética…'}</div>}
export function Kpi({label,value,current,previous,note}){let change=null;if(current!==undefined&&previous!==undefined&&previous!==0)change=((current-previous)/previous)*100;return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</div><div className="mt-2 text-2xl font-bold text-slate-900">{value}</div>{change!==null&&<div className={`mt-1 text-xs font-semibold ${change>0?'text-amber-700':change<0?'text-emerald-700':'text-slate-500'}`}>{pct(change)} vs jul 2025</div>}{note&&<div className="mt-1 text-xs text-slate-500">{note}</div>}</div>}
export function Card({title,subtitle,children,className=''}){return <section className={`rounded-2xl border border-slate-200 bg-white p-5 shadow-sm ${className}`}><div><h2 className="font-semibold text-slate-900">{title}</h2>{subtitle&&<p className="mt-1 text-xs text-slate-500">{subtitle}</p>}</div>{children}</section>}
export function Header({title,subtitle}){return <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-xs font-bold uppercase tracking-[.18em] text-emerald-700">SIDCO · Inteligencia de incendios</div><h1 className="mt-1 text-2xl font-bold text-slate-900">{title}</h1><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div><div className="flex flex-wrap gap-2"><span className="chip">Julio 2026</span><span className="chip">Comparación: julio 2025</span><span className="chip">Sur de Chile</span></div></div>}
export function Page({children}){return <section className="space-y-5">{children}</section>}
export function SimpleTable({rows,columns,onClick}){return <div className="mt-4 overflow-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b text-[10px] uppercase text-slate-500">{columns.map(c=><th className="px-2 py-2" key={c.key}>{c.label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} onClick={()=>onClick?.(r)} className={`border-b border-slate-100 ${onClick?'cursor-pointer hover:bg-slate-50':''}`}>{columns.map(c=><td className="px-2 py-2 text-slate-700" key={c.key}>{c.render?c.render(r):r[c.key]}</td>)}</tr>)}</tbody></table></div>}
